spring.application.name=@project.name@
server.port=8081

gate-service.uri=localhost:8080
user-service.uri=localhost:8082
sudsandbuds-app.uri=localhost:4200
open-brewery-api.uri=https://api.openbrewerydb.org/v1